/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.MyTest;
import com.mycompany.myapp.dto.MyTestDTO;
import com.mycompany.myapp.dto.MyTestDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.MyTestRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/myTests")
public class MyTestResource {

    private final Logger log = LoggerFactory.getLogger(MyTestResource.class);

    @Inject
    private MyTestRepository myTestRepository;
    @Inject
    private MyTestDTOService myTestDTOService;

    /**
     * Create a new MyTest.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<MyTestDTO> create(@RequestBody MyTestDTO myTestDTO) throws URISyntaxException {

        log.debug("Create MyTestDTO : {}", myTestDTO);

        if (myTestDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create MyTest with existing ID").body(null);
        }

        MyTestDTO result = myTestDTOService.save(myTestDTO);

        return ResponseEntity.created(new URI("/api/myTests/" + result.id)).body(result);
    }

    /**
    * Find by id MyTest.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<MyTestDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id MyTest : {}", id);

        return Optional.ofNullable(myTestDTOService.findOne(id)).map(myTestDTO -> new ResponseEntity<>(myTestDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update MyTest.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<MyTestDTO> update(@RequestBody MyTestDTO myTestDTO) throws URISyntaxException {

        log.debug("Update MyTestDTO : {}", myTestDTO);

        if (!myTestDTO.isIdSet()) {
            return create(myTestDTO);
        }

        MyTestDTO result = myTestDTOService.save(myTestDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of MyTest using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<MyTestDTO>> findAll(@RequestBody PageRequestByExample<MyTestDTO> prbe) throws URISyntaxException {
        PageResponse<MyTestDTO> pageResponse = myTestDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<MyTestDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<MyTestDTO> results = myTestDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id MyTest.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id MyTest : {}", id);

        try {
            myTestRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}