//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class MyTest {
    // Raw attributes
    id : number;
    firstName : string;
    lastName : string;
    dateOfJoining : Date;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.firstName = json.firstName;
            this.lastName = json.lastName;
            if (json.dateOfJoining != null) {
                this.dateOfJoining = new Date(json.dateOfJoining);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : MyTest[] {
        let myTests : MyTest[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                myTests.push(new MyTest(json));
            }
        }
        return myTests;
    }
}
