/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.time.Instant;
import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for Warehouse.
 */
public class WarehouseDTO {
    public Integer id;
    public String name;
    public Double rating;
    public String type;
    public String description;
    public String address;
    public String phone1;
    public String phone2;
    public String fulfilmentType;
    public Double storagePrice;
    public LocalDate minHirePeriod;
    public Double deposit;
    public Integer facilitySize;
    public Integer facilitySizeUom;
    public Integer storageSize;
    public Integer storageSizeUom;
    public String operatingDays;
    public String operatingHours;
    public Integer noOfReceivingDoors;
    public Integer noOfShippingDoors;
    public String wmsVendor;
    public String racking;
    public Double maxStorageHeight;
    public Double maxStorageHeightUom;
    public Double maxStorageWeight;
    public Double maxStorageWeightUom;
    public String handlingEquipment;
    public String temperatureRange;
    public String structureType;
    public Integer yearOfConstruction;
    public String fleetAccess;
    public String powerSanctioned;
    public String waterConnection;
    public String powerBackup;
    public String craneServices;
    public String fireSystems;
    public String security;
    public String lift;
    public String toilet;
    public String parking;
    public Double distanceFromMainRoad;
    public Double yard;
    public String facilityCertification;
    public String faciltiyInsurance;
    public Double importExport;
    public String inboundServices;
    public String outboundServices;
    public String valueAddedServices;
    public Double laborServices;
    public Double totalLabor;
    public String distributionServices;
    public Instant creationDate;
    public String creationAuthor;
    public Instant lastModificationDate;
    public String lastModificationAuthor;
    public Integer version;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}